[tool.poetry]
name = "etl"
version = "0.1.0"
description = "Dagster ETL for Wikipedia data."
authors = ["imlapps"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
dagster = "^1.7.9"
pydantic = "^2.7.4"
dagster-webserver = "^1.7.9"
unidecode = "^1.3.8"
langchain = "^0.2.5"
langchain-openai = "^0.1.8"
langchain-community = "^0.2.5"
faiss-cpu = "^1.8.0.post1"
pyoxigraph = "^0.3.22"

[tool.dagster]
module_name = "etl" 

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
mypy = "^1.10.0"
ruff = "^0.4.8"
pytest = "^8.2.2"
isort = "^5.13.2"
tee = "^0.0.3"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"